"""empty message

Revision ID: 0b41b4578538
Revises: 5a7dcb95a179
Create Date: 2023-10-06 12:10:22.089850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b41b4578538'
down_revision = '5a7dcb95a179'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('two_point_attempts', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('two_point_made', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('three_point_attempts', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('three_point_made', sa.Integer(), nullable=False))
        batch_op.drop_column('field_goal_made')
        batch_op.drop_column('field_goal_attempts')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field_goal_attempts', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('field_goal_made', sa.INTEGER(), nullable=False))
        batch_op.drop_column('three_point_made')
        batch_op.drop_column('three_point_attempts')
        batch_op.drop_column('two_point_made')
        batch_op.drop_column('two_point_attempts')

    # ### end Alembic commands ###
