"""empty message

Revision ID: 2ba35b864546
Revises: 
Create Date: 2023-10-05 11:37:23.769437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ba35b864546'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('control_values',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('field_goals', sa.Integer(), nullable=True),
    sa.Column('field_goal_attempts', sa.Integer(), nullable=True),
    sa.Column('field_goal_percentage', sa.Float(), server_default='0', nullable=True),
    sa.Column('three_pointers', sa.Integer(), nullable=True),
    sa.Column('three_point_attempts', sa.Integer(), nullable=True),
    sa.Column('three_point_percentage', sa.Float(), server_default='0', nullable=True),
    sa.Column('two_pointers', sa.Integer(), nullable=True),
    sa.Column('two_point_attempts', sa.Integer(), nullable=True),
    sa.Column('two_point_percentage', sa.Float(), server_default='0', nullable=True),
    sa.Column('free_throws', sa.Integer(), nullable=True),
    sa.Column('free_throw_attempts', sa.Integer(), nullable=True),
    sa.Column('free_throw_percentage', sa.Float(), server_default='0', nullable=True),
    sa.Column('offensive_rebounds', sa.Integer(), nullable=True),
    sa.Column('defensive_rebounds', sa.Integer(), nullable=True),
    sa.Column('total_rebounds', sa.Integer(), server_default='0', nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('steals', sa.Integer(), nullable=True),
    sa.Column('blocks', sa.Integer(), nullable=True),
    sa.Column('turnovers', sa.Integer(), nullable=True),
    sa.Column('personal_fouls', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), server_default='0', nullable=True),
    sa.Column('player_efficiency_rating', sa.Float(), server_default='0', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('logo', sa.String(length=128), nullable=True),
    sa.Column('abbreviation', sa.String(length=3), nullable=True),
    sa.Column('conference', sa.String(length=32), nullable=True),
    sa.Column('division', sa.String(length=32), nullable=True),
    sa.Column('court', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('season', sa.String(length=32), nullable=True),
    sa.Column('season_type', sa.String(length=32), nullable=True),
    sa.Column('start_date', sa.String(length=32), nullable=True),
    sa.Column('end_date', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.String(length=32), nullable=True),
    sa.Column('local_team_id', sa.String(length=32), nullable=False),
    sa.Column('visitor_team_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['local_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['visitor_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('date_of_birth', sa.String(length=64), nullable=True),
    sa.Column('picture', sa.String(length=64), nullable=True),
    sa.Column('position', sa.String(length=64), nullable=True),
    sa.Column('historical_team_id', sa.String(length=64), nullable=True),
    sa.Column('games', sa.Integer(), nullable=True),
    sa.Column('games_started', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('stats_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stats_id'], ['stats.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('stats_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['stats_id'], ['stats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games_tournament',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('stats_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['stats_id'], ['stats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('actual_team', sa.Boolean(), nullable=True),
    sa.Column('beggining_of_contract', sa.Date(), nullable=True),
    sa.Column('end_of_contract', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_history')
    op.drop_table('player_stats')
    op.drop_table('games_tournament')
    op.drop_table('games_stats')
    op.drop_table('team_stats')
    op.drop_table('players')
    op.drop_table('games')
    op.drop_table('tournaments')
    op.drop_table('teams')
    op.drop_table('stats')
    op.drop_table('control_values')
    # ### end Alembic commands ###
