"""empty message

Revision ID: 549bb54c963b
Revises: 2ba35b864546
Create Date: 2023-10-05 12:02:10.661883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '549bb54c963b'
down_revision = '2ba35b864546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games_tournament')
    op.drop_table('games_stats')
    op.drop_table('players')
    op.drop_table('control_values')
    op.drop_table('teams')
    op.drop_table('player_stats')
    op.drop_table('stats')
    op.drop_table('tournaments')
    op.drop_table('team_stats')
    op.drop_table('games')
    op.drop_table('team_history')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('player_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('team_id', sa.INTEGER(), nullable=True),
    sa.Column('actual_team', sa.BOOLEAN(), nullable=True),
    sa.Column('beggining_of_contract', sa.DATE(), nullable=True),
    sa.Column('end_of_contract', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.VARCHAR(length=32), nullable=True),
    sa.Column('local_team_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('visitor_team_id', sa.VARCHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['local_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['visitor_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_stats',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('team_id', sa.INTEGER(), nullable=True),
    sa.Column('stats_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['stats_id'], ['stats.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournaments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('season', sa.VARCHAR(length=32), nullable=True),
    sa.Column('season_type', sa.VARCHAR(length=32), nullable=True),
    sa.Column('start_date', sa.VARCHAR(length=32), nullable=True),
    sa.Column('end_date', sa.VARCHAR(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stats',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('games_played', sa.INTEGER(), nullable=True),
    sa.Column('field_goals', sa.INTEGER(), nullable=True),
    sa.Column('field_goal_attempts', sa.INTEGER(), nullable=True),
    sa.Column('field_goal_percentage', sa.FLOAT(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('three_pointers', sa.INTEGER(), nullable=True),
    sa.Column('three_point_attempts', sa.INTEGER(), nullable=True),
    sa.Column('three_point_percentage', sa.FLOAT(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('two_pointers', sa.INTEGER(), nullable=True),
    sa.Column('two_point_attempts', sa.INTEGER(), nullable=True),
    sa.Column('two_point_percentage', sa.FLOAT(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('free_throws', sa.INTEGER(), nullable=True),
    sa.Column('free_throw_attempts', sa.INTEGER(), nullable=True),
    sa.Column('free_throw_percentage', sa.FLOAT(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('offensive_rebounds', sa.INTEGER(), nullable=True),
    sa.Column('defensive_rebounds', sa.INTEGER(), nullable=True),
    sa.Column('total_rebounds', sa.INTEGER(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('assists', sa.INTEGER(), nullable=True),
    sa.Column('steals', sa.INTEGER(), nullable=True),
    sa.Column('blocks', sa.INTEGER(), nullable=True),
    sa.Column('turnovers', sa.INTEGER(), nullable=True),
    sa.Column('personal_fouls', sa.INTEGER(), nullable=True),
    sa.Column('points', sa.INTEGER(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('player_efficiency_rating', sa.FLOAT(), server_default=sa.text("'0'"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_stats',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('player_id', sa.INTEGER(), nullable=True),
    sa.Column('stats_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['stats_id'], ['stats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('city', sa.VARCHAR(length=64), nullable=True),
    sa.Column('logo', sa.VARCHAR(length=128), nullable=True),
    sa.Column('abbreviation', sa.VARCHAR(length=3), nullable=True),
    sa.Column('conference', sa.VARCHAR(length=32), nullable=True),
    sa.Column('division', sa.VARCHAR(length=32), nullable=True),
    sa.Column('court', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('control_values',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('value', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('date_of_birth', sa.VARCHAR(length=64), nullable=True),
    sa.Column('picture', sa.VARCHAR(length=64), nullable=True),
    sa.Column('position', sa.VARCHAR(length=64), nullable=True),
    sa.Column('historical_team_id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('games', sa.INTEGER(), nullable=True),
    sa.Column('games_started', sa.INTEGER(), nullable=True),
    sa.Column('team_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games_stats',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('game_id', sa.INTEGER(), nullable=True),
    sa.Column('stats_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['stats_id'], ['stats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games_tournament',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('game_id', sa.INTEGER(), nullable=True),
    sa.Column('tournament_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
