"""empty message

Revision ID: 5a7dcb95a179
Revises: 8e64b3d6698f
Create Date: 2023-10-06 11:58:04.620096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a7dcb95a179'
down_revision = '8e64b3d6698f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field_goal_attempts', sa.Integer(), nullable=False))
        batch_op.drop_column('field_goal_attemps')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field_goal_attemps', sa.INTEGER(), nullable=False))
        batch_op.drop_column('field_goal_attempts')

    # ### end Alembic commands ###
