from db import db

class Game(db.Model):
    __tablename__ = "games"
    id = db.Column(db.String(32), primary_key=True)
    date = db.Column(db.Date, nullable=False)
    local_team_id = db.Column(db.String(32), db.ForeignKey("teams.id"), nullable=False)
    visitor_team_id = db.Column(db.String(32), db.ForeignKey("teams.id"), nullable=False)
    local_team = db.relationship("Team", foreign_keys=[local_team_id])
    visitor_team = db.relationship("Team", foreign_keys=[visitor_team_id])
    local_score = db.Column(db.Integer, nullable=False)
    visitor_score = db.Column(db.Integer, nullable=False)
    date = db.Column(db.Date, nullable=False)
    season = db.Column(db.String(32), nullable=False)
    season_type = db.Column(db.String(32), nullable=False)
    status = db.Column(db.String(32), nullable=False)
    post_season = db.Column(db.Boolean, nullable=False)
    home_team_wins = db.Column(db.Boolean, nullable=False)
    visitor_team_wins = db.Column(db.Boolean, nullable=False)
    local_players = db.relationship("Player", secondary="stats", lazy="subquery", foreign_keys="Stats.local_player_id")
    local_players_stats = db.relationship("Stats", lazy="subquery", foreign_keys="Stats.local_player_id")
    visitor_players = db.relationship("Player", secondary="stats", lazy="subquery", foreign_keys="Stats.visitor_player_id")
    visitor_players_stats = db.relationship("Stats", lazy="subquery", foreign_keys="Stats.visitor_player_id")
    local_team_stats = db.relationship("Stats", lazy="subquery", foreign_keys="Stats.local_team_id")
    visitor_team_stats = db.relationship("Stats", lazy="subquery", foreign_keys="Stats.visitor_team_id")